import Head from 'next/head'
import Image from 'next/image'
import Card from '../component/Card'
import styles from '../styles/Home.module.css'
import Navbar from '../component/Navbar'
import Section1 from '../component/Section1'
import Section2 from '../component/Section2'
import Section3 from '../component/Section3'
import Footer from '../component/Footer1'
import Footer1 from '../component/Footer1'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   

     <Navbar/>
     <Section1/>
     <Section2/>
     <Section3/>
     <Footer1/>
    </div>
  )
}
